/*
 * Speechmatics ASR REST API
 *
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 * Generated by: https://openapi-generator.tech
 */

use crate::batch::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TranscriptionConfigSpeakerDiarizationConfigSpeakers {
    /// Speaker label, which must not match the format used internally (e.g. S1, S2, etc); Possible values: non-empty
    #[serde(rename = "label")]
    pub label: String,

    /// Possible values: >= 1
    #[serde(rename = "speaker_identifiers")]
    pub speaker_identifiers: Vec<bytes>,
}

impl TranscriptionConfigSpeakerDiarizationConfigSpeakers {
    pub fn new(
        label: String,
        speaker_identifiers: Vec<bytes::Bytes>,
    ) -> TranscriptionConfigSpeakerDiarizationConfigSpeakers {
        TranscriptionConfigSpeakerDiarizationConfigSpeakers {
            label,
            speaker_identifiers,
        }
    }
}
